import {useState,type ReactNode} from 'react';
import {Icon} from './ui/Icon';
import {useAppearance,type Theme} from './ui/appearance';
export const states=['Todas','Descargando','En cola','Completadas','Pausadas','Fallidas'];
export const categories=['Videos','Documentos','Programas','Comprimidos','Otros'];
export function App({connection,children}:{connection:ReactNode,children?:ReactNode}){
 const {theme,setTheme}=useAppearance();const [view,setView]=useState('Todas');const [collapsed,setCollapsed]=useState(false);
 return <div className={'app-shell'+(collapsed?' collapsed':'')}><aside className="sidebar"><div className="brand"><span className="brand-mark"><Icon name="download"/></span><strong>IDG</strong><span className="muted brand-caption">Download Genious</span></div><nav aria-label="Descargas"><small>DESCARGAS</small>{states.map((s,i)=><button key={s} aria-current={view===s?'page':undefined} onClick={()=>setView(s)}><Icon name={['folder','download','clock','check','pause','error'][i]}/><span>{s}</span></button>)}<small>CATEGORÍAS</small>{categories.map((s,i)=><button key={s} aria-current={view===s?'page':undefined} onClick={()=>setView(s)}><Icon name={['video','file','code','box','folder'][i]}/><span>{s}</span></button>)}</nav><div className="sidebar-bottom"><label>Tema<select aria-label="Tema" value={theme} onChange={e=>setTheme(e.target.value as Theme)}><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></label><small className="muted">Desarrollo · fase 02</small></div></aside><div className="workspace"><header className="toolbar"><button aria-label={collapsed?'Mostrar sidebar':'Contraer sidebar'} onClick={()=>setCollapsed(!collapsed)}><Icon name="menu"/></button><label className="search"><Icon name="search"/><input type="search" placeholder="Buscar descargas…" aria-label="Buscar descargas"/></label><button disabled>Filtros</button><button disabled className="primary"><Icon name="plus"/>Nueva descarga</button></header><main><div className="view-heading"><div><p className="eyebrow">TU BIBLIOTECA</p><h1>{view==='Todas'?'Todas las descargas':view}</h1></div><span className="muted">0 archivos</span></div>{children??<section className="empty"><span className="empty-icon"><Icon name="download" size={26}/></span><h2>Todo listo para empezar</h2><p>Tu lista de descargas aparecerá aquí.</p><p className="muted">El motor de descargas todavía no está disponible.</p></section>}</main>{connection}</div></div>;
}
