// Generated by cargo run -p idg-protocol --bin export-types.
export type StartPolicy = "now" | "later" | "queue";
export type CreateDownload = { input: NewDownload, options: TransferOptions, category: string, start: StartPolicy, };
export type AppPreferences = { welcome_done: boolean, directory: string, theme: string, view: string, close_action: string, autopick_mode: string, notify_completed: boolean, notify_failed: boolean, mini_window: boolean, drop_target: boolean, queue_running: boolean, };
export type RequestMode = "automatic" | { "manual": { requests: number, } };
export type Priority = "high" | "normal" | "low";
export type TransferOptions = { mode: RequestMode,
/**
 * Explicit caller assertion that this GET may safely be repeated in parallel.
 */
replay_safe: boolean, bytes_per_second: number | null, priority: Priority, };
export type ResourceLimits = { max_downloads: number, global_requests: number, origin_requests: number, bytes_per_second: number | null, };
export type RangeSnapshot = { start: string, end_exclusive: string, durable: boolean, };
export type ResumeCapability = "unknown" | "validator_available" | "range_verified";
export type IntegrityState = "not_checked" | "calculated" | "verified" | "mismatch";
export type ConflictPolicy = "rename" | "reject" | "replace";
export type NewDownload = { url: string, directory: string, name: string, expected_sha256: string | null, conflict: ConflictPolicy, };
export type TransferState = "deferred" | "queued" | "probing" | "downloading" | "paused" | "verifying" | "publish_pending" | "completed" | "failed" | "cancelled";
export type DownloadError = "invalid_input" | "busy" | "not_found" | "invalid_state" | "conflict" | "storage" | "network" | "timeout" | "tls" | "access_denied" | "retry_later" | "http_status" | "unsafe_resume" | "resource_changed" | "range_ignored" | "invalid_range" | "expired" | "representation" | "size_mismatch" | "hash_mismatch" | "partial_changed" | "disk_full" | "file_io" | "publish_blocked" | "secret_unavailable";
export type UnavailableDownload = { id: string, error: DownloadError, };
export type DownloadSnapshot = { category: string, domain: string, created_at: string, options: TransferOptions, active_requests: number, target_requests: number, ranges_total: number, ranges_durable: number, transferred_bytes: string, retries: number, strategy: string, resume_capability: ResumeCapability, integrity: IntegrityState, id: string, name: string, state: TransferState, received_bytes: string, durable_bytes: string, total_bytes: string | null, resume: string, calculated_sha256: string | null, verified_against_reference: boolean, error: DownloadError | null, message: string | null, retry_after_seconds: number | null, };
export type Command = { "find_recoverable_download": { input: NewDownload, } } | { "create_download": { draft: CreateDownload, } } | "get_app_preferences" | { "get_download_directory": { job_id: string, } } | { "set_app_preferences": { preferences: AppPreferences, } } | "handshake" | "ping" | "get_snapshot" | "subscribe" | "shutdown" | "get_download_capabilities" | { "add_download": { input: NewDownload, } } | { "add_download_with_options": { input: NewDownload, options: TransferOptions, } } | { "set_download_options": { job_id: string, options: TransferOptions, } } | { "set_resource_limits": { limits: ResourceLimits, } } | "get_resource_limits" | { "get_download_ranges": { job_id: string, offset: number, } } | { "get_download": { job_id: string, } } | { "list_downloads": { offset: number, } } | { "pause_download": { job_id: string, } } | { "resume_download": { job_id: string, } } | { "cancel_download": { job_id: string, } };
export type ErrorCode = "invalid_message" | "incompatible_version" | "handshake_required" | "unauthorized" | "unavailable" | "timeout";
export type Snapshot = { native_hosts: number, runtime_id: string, process_id: number, sequence: number, clients: number, stopping: boolean, };
export type Payload = { "kind": "recoverable_download", job_id: string | null, } | { "kind": "download_directory", directory: string, } | { "kind": "app_preferences", preferences: AppPreferences, } | { "kind": "resource_limits", limits: ResourceLimits, } | { "kind": "download_ranges", ranges: Array<RangeSnapshot>, next_offset: number | null, } | { "kind": "download_capabilities", operations: Array<string>, schema_version: number, max_active: number, max_write_bytes: number, strong_validator_required: boolean, } | { "kind": "download_changed", sequence: number, job: DownloadSnapshot, } | { "kind": "hello", capabilities: Array<Command>, snapshot: Snapshot, } | { "kind": "pong" } | { "kind": "snapshot", snapshot: Snapshot, } | { "kind": "subscribed", snapshot: Snapshot, } | { "kind": "stopping" } | { "kind": "error", code: ErrorCode, } | { "kind": "download", job: DownloadSnapshot, } | { "kind": "downloads", unavailable: Array<UnavailableDownload>, jobs: Array<DownloadSnapshot>, next_offset: number | null, } | { "kind": "download_failure", code: DownloadError, message: string, };
export type Request = { version: number, id: string, command: Command, };
export type Response = { version: number, id: string, payload: Payload, };
export type ConnectionState = { connected: boolean, snapshot: Snapshot | null, error: string | null, };
